#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum ReferenceType {
    Config,
    DictionaryField,
    Constant,
    Enum,
    EnumMember,
    Model,
    ModelField,
    Interface,
    InterfaceField,
    Middleware,
    DataSet,
    DataSetRecord,
    DecoratorDeclaration,
    PipelineItemDeclaration,
    StructDeclaration,
    StructInstanceFunction,
    StructStaticFunction,
    FunctionDeclaration,
    Namespace,
}