use std::fmt::{Display, Formatter};
use educe::Educe;
use serde::Serialize;
use crate::r#type::Type;

#[derive(Debug, Clone, Eq, Serialize)]
#[derive(Educe)]
#[educe(Hash, PartialEq)]
pub enum ShapeReference {
    BoolFilter,
    BoolNullableFilter,
    IntFilter,
    IntNullableFilter,
    Int64Filter,
    Int64NullableFilter,
    Float32Filter,
    Float32NullableFilter,
    FloatFilter,
    FloatNullableFilter,
    DecimalFilter,
    DecimalNullableFilter,
    DateFilter,
    DateNullableFilter,
    DateTimeFilter,
    DateTimeNullableFilter,
    ObjectIdFilter,
    ObjectIdNullableFilter,
    StringFilter,
    StringNullableFilter,
    EnumFilter(Box<Type>),
    EnumNullableFilter(Box<Type>),
    ArrayFilter(Box<Type>),
    ArrayNullableFilter(Box<Type>),
    BoolWithAggregatesFilter,
    BoolNullableWithAggregatesFilter,
    IntWithAggregatesFilter,
    IntNullableWithAggregatesFilter,
    Int64WithAggregatesFilter,
    Int64NullableWithAggregatesFilter,
    Float32WithAggregatesFilter,
    Float32NullableWithAggregatesFilter,
    FloatWithAggregatesFilter,
    FloatNullableWithAggregatesFilter,
    DecimalWithAggregatesFilter,
    DecimalNullableWithAggregatesFilter,
    DateWithAggregatesFilter,
    DateNullableWithAggregatesFilter,
    DateTimeWithAggregatesFilter,
    DateTimeNullableWithAggregatesFilter,
    ObjectIdWithAggregatesFilter,
    ObjectIdNullableWithAggregatesFilter,
    StringWithAggregatesFilter,
    StringNullableWithAggregatesFilter,
    EnumWithAggregatesFilter(Box<Type>),
    EnumNullableWithAggregatesFilter(Box<Type>),
    ArrayWithAggregatesFilter(Box<Type>),
    ArrayNullableWithAggregatesFilter(Box<Type>),
    IntAtomicUpdateOperationInput,
    Int64AtomicUpdateOperationInput,
    Float32AtomicUpdateOperationInput,
    FloatAtomicUpdateOperationInput,
    DecimalAtomicUpdateOperationInput,
    ArrayAtomicUpdateOperationInput(Box<Type>),
    Args(Vec<usize>, Vec<String>),
    FindManyArgs(Vec<usize>, Vec<String>),
    FindFirstArgs(Vec<usize>, Vec<String>),
    FindUniqueArgs(Vec<usize>, Vec<String>),
    CreateArgs(Vec<usize>, Vec<String>),
    UpdateArgs(Vec<usize>, Vec<String>),
    UpsertArgs(Vec<usize>, Vec<String>),
    CopyArgs(Vec<usize>, Vec<String>),
    DeleteArgs(Vec<usize>, Vec<String>),
    CreateManyArgs(Vec<usize>, Vec<String>),
    UpdateManyArgs(Vec<usize>, Vec<String>),
    CopyManyArgs(Vec<usize>, Vec<String>),
    DeleteManyArgs(Vec<usize>, Vec<String>),
    CountArgs(Vec<usize>, Vec<String>),
    AggregateArgs(Vec<usize>, Vec<String>),
    GroupByArgs(Vec<usize>, Vec<String>),
    RelationFilter(Vec<usize>, Vec<String>),
    ListRelationFilter(Vec<usize>, Vec<String>),
    WhereInput(Vec<usize>, Vec<String>),
    WhereUniqueInput(Vec<usize>, Vec<String>),
    ScalarWhereWithAggregatesInput(Vec<usize>, Vec<String>),
    CreateInput(Vec<usize>, Vec<String>),
    CreateInputWithout(Vec<usize>, Vec<String>, String),
    CreateNestedOneInput(Vec<usize>, Vec<String>),
    CreateNestedOneInputWithout(Vec<usize>, Vec<String>, String),
    CreateNestedManyInput(Vec<usize>, Vec<String>),
    CreateNestedManyInputWithout(Vec<usize>, Vec<String>, String),
    UpdateInput(Vec<usize>, Vec<String>),
    UpdateInputWithout(Vec<usize>, Vec<String>, String),
    UpdateNestedOneInput(Vec<usize>, Vec<String>),
    UpdateNestedOneInputWithout(Vec<usize>, Vec<String>, String),
    UpdateNestedManyInput(Vec<usize>, Vec<String>),
    UpdateNestedManyInputWithout(Vec<usize>, Vec<String>, String),
    ConnectOrCreateInput(Vec<usize>, Vec<String>),
    ConnectOrCreateInputWithout(Vec<usize>, Vec<String>, String),
    UpdateWithWhereUniqueInput(Vec<usize>, Vec<String>),
    UpdateWithWhereUniqueInputWithout(Vec<usize>, Vec<String>, String),
    UpsertWithWhereUniqueInput(Vec<usize>, Vec<String>),
    UpsertWithWhereUniqueInputWithout(Vec<usize>, Vec<String>, String),
    UpdateManyWithWhereInput(Vec<usize>, Vec<String>),
    UpdateManyWithWhereInputWithout(Vec<usize>, Vec<String>, String),
    Select(Vec<usize>, Vec<String>),
    Include(Vec<usize>, Vec<String>),
    OrderByInput(Vec<usize>, Vec<String>),
}

impl Display for ShapeReference {

    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            ShapeReference::BoolFilter => f.write_str("BoolFilter"),
            ShapeReference::BoolNullableFilter => f.write_str("BoolNullableFilter"),
            ShapeReference::IntFilter => f.write_str("IntFilter"),
            ShapeReference::IntNullableFilter => f.write_str("IntNullableFilter"),
            ShapeReference::Int64Filter => f.write_str("Int64Filter"),
            ShapeReference::Int64NullableFilter => f.write_str("Int64NullableFilter"),
            ShapeReference::Float32Filter => f.write_str("Float32Filter"),
            ShapeReference::Float32NullableFilter => f.write_str("Float32NullableFilter"),
            ShapeReference::FloatFilter => f.write_str("FloatFilter"),
            ShapeReference::FloatNullableFilter => f.write_str("FloatNullableFilter"),
            ShapeReference::DecimalFilter => f.write_str("DecimalFilter"),
            ShapeReference::DecimalNullableFilter => f.write_str("DecimalNullableFilter"),
            ShapeReference::DateFilter => f.write_str("DateFilter"),
            ShapeReference::DateNullableFilter => f.write_str("DateNullableFilter"),
            ShapeReference::DateTimeFilter => f.write_str("DateTimeFilter"),
            ShapeReference::DateTimeNullableFilter => f.write_str("DateTimeNullableFilter"),
            ShapeReference::ObjectIdFilter => f.write_str("ObjectIdFilter"),
            ShapeReference::ObjectIdNullableFilter => f.write_str("ObjectIdNullableFilter"),
            ShapeReference::StringFilter => f.write_str("StringFilter"),
            ShapeReference::StringNullableFilter => f.write_str("StringNullableFilter"),
            ShapeReference::EnumFilter(t) => f.write_str(&format!("EnumFilter<{}>", t.as_ref())),
            ShapeReference::EnumNullableFilter(t) => f.write_str(&format!("EnumNullableFilter<{}>", t.as_ref())),
            ShapeReference::ArrayFilter(t) => f.write_str(&format!("ArrayFilter<{}>", t.as_ref())),
            ShapeReference::ArrayNullableFilter(t) => f.write_str(&format!("ArrayNullableFilter<{}>", t.as_ref())),
            ShapeReference::BoolWithAggregatesFilter => f.write_str("BoolWithAggregatesFilter"),
            ShapeReference::BoolNullableWithAggregatesFilter => f.write_str("BoolNullableWithAggregatesFilter"),
            ShapeReference::IntWithAggregatesFilter => f.write_str("IntWithAggregatesFilter"),
            ShapeReference::IntNullableWithAggregatesFilter => f.write_str("IntNullableWithAggregatesFilter"),
            ShapeReference::Int64WithAggregatesFilter => f.write_str("Int64WithAggregatesFilter"),
            ShapeReference::Int64NullableWithAggregatesFilter => f.write_str("Int64NullableWithAggregatesFilter"),
            ShapeReference::Float32WithAggregatesFilter => f.write_str("Float32WithAggregatesFilter"),
            ShapeReference::Float32NullableWithAggregatesFilter => f.write_str("Float32NullableWithAggregatesFilter"),
            ShapeReference::FloatWithAggregatesFilter => f.write_str("FloatWithAggregatesFilter"),
            ShapeReference::FloatNullableWithAggregatesFilter => f.write_str("FloatNullableWithAggregatesFilter"),
            ShapeReference::DecimalWithAggregatesFilter => f.write_str("DecimalWithAggregatesFilter"),
            ShapeReference::DecimalNullableWithAggregatesFilter => f.write_str("DecimalNullableWithAggregatesFilter"),
            ShapeReference::DateWithAggregatesFilter => f.write_str("DateWithAggregatesFilter"),
            ShapeReference::DateNullableWithAggregatesFilter => f.write_str("DateNullableWithAggregatesFilter"),
            ShapeReference::DateTimeWithAggregatesFilter => f.write_str("DateTimeWithAggregatesFilter"),
            ShapeReference::DateTimeNullableWithAggregatesFilter => f.write_str("DateTimeNullableWithAggregatesFilter"),
            ShapeReference::ObjectIdWithAggregatesFilter => f.write_str("ObjectIdWithAggregatesFilter"),
            ShapeReference::ObjectIdNullableWithAggregatesFilter => f.write_str("ObjectIdNullableWithAggregatesFilter"),
            ShapeReference::StringWithAggregatesFilter => f.write_str("StringWithAggregatesFilter"),
            ShapeReference::StringNullableWithAggregatesFilter => f.write_str("StringNullableWithAggregatesFilter"),
            ShapeReference::EnumWithAggregatesFilter(t) => f.write_str(&format!("EnumWithAggregatesFilter<{}>", t.as_ref())),
            ShapeReference::EnumNullableWithAggregatesFilter(t) => f.write_str(&format!("EnumNullableWithAggregatesFilter<{}>", t.as_ref())),
            ShapeReference::ArrayWithAggregatesFilter(t) => f.write_str(&format!("ArrayWithAggregatesFilter<{}>", t.as_ref())),
            ShapeReference::ArrayNullableWithAggregatesFilter(t) => f.write_str(&format!("ArrayNullableWithAggregatesFilter<{}>", t.as_ref())),
            ShapeReference::IntAtomicUpdateOperationInput => f.write_str("IntAtomicUpdateOperationInput"),
            ShapeReference::Int64AtomicUpdateOperationInput => f.write_str("Int64AtomicUpdateOperationInput"),
            ShapeReference::Float32AtomicUpdateOperationInput => f.write_str("Float32AtomicUpdateOperationInput"),
            ShapeReference::FloatAtomicUpdateOperationInput => f.write_str("FloatAtomicUpdateOperationInput"),
            ShapeReference::DecimalAtomicUpdateOperationInput => f.write_str("DecimalAtomicUpdateOperationInput"),
            ShapeReference::ArrayAtomicUpdateOperationInput(t) => f.write_str(&format!("ArrayAtomicUpdateOperationInput{}", t.as_ref())),
            ShapeReference::Args(_, k) => f.write_str(&format!("Args<{}>", k.join("."))),
            ShapeReference::FindManyArgs(_, k) => f.write_str(&format!("FindManyArgs<{}>", k.join("."))),
            ShapeReference::FindFirstArgs(_, k) => f.write_str(&format!("FindFirstArgs<{}>", k.join("."))),
            ShapeReference::FindUniqueArgs(_, k) => f.write_str(&format!("FindUniqueArgs<{}>", k.join("."))),
            ShapeReference::CreateArgs(_, k) => f.write_str(&format!("CreateArgs<{}>", k.join("."))),
            ShapeReference::UpdateArgs(_, k) => f.write_str(&format!("UpdateArgs<{}>", k.join("."))),
            ShapeReference::UpsertArgs(_, k) => f.write_str(&format!("UpsertArgs<{}>", k.join("."))),
            ShapeReference::CopyArgs(_, k) => f.write_str(&format!("CopyArgs<{}>", k.join("."))),
            ShapeReference::DeleteArgs(_, k) => f.write_str(&format!("DeleteArgs<{}>", k.join("."))),
            ShapeReference::CreateManyArgs(_, k) => f.write_str(&format!("CreateManyArgs<{}>", k.join("."))),
            ShapeReference::UpdateManyArgs(_, k) => f.write_str(&format!("UpdateManyArgs<{}>", k.join("."))),
            ShapeReference::CopyManyArgs(_, k) => f.write_str(&format!("CopyManyArgs<{}>", k.join("."))),
            ShapeReference::DeleteManyArgs(_, k) => f.write_str(&format!("DeleteManyArgs<{}>", k.join("."))),
            ShapeReference::CountArgs(_, k) => f.write_str(&format!("CountArgs<{}>", k.join("."))),
            ShapeReference::AggregateArgs(_, k) => f.write_str(&format!("AggregateArgs<{}>", k.join("."))),
            ShapeReference::GroupByArgs(_, k) => f.write_str(&format!("GroupByArgs<{}>", k.join("."))),
            ShapeReference::RelationFilter(_, k) => f.write_str(&format!("RelationFilter<{}>", k.join("."))),
            ShapeReference::ListRelationFilter(_, k) => f.write_str(&format!("ListRelationFilter<{}>", k.join("."))),
            ShapeReference::WhereInput(_, k) => f.write_str(&format!("WhereInput<{}>", k.join("."))),
            ShapeReference::WhereUniqueInput(_, k) => f.write_str(&format!("WhereUniqueInput<{}>", k.join("."))),
            ShapeReference::ScalarWhereWithAggregatesInput(_, k) => f.write_str(&format!("ScalarWhereWithAggregatesInput<{}>", k.join("."))),
            ShapeReference::CreateInput(_, k) => f.write_str(&format!("CreateInput<{}>", k.join("."))),
            ShapeReference::CreateInputWithout(_, k, r) => f.write_str(&format!("CreateInputWithout<{}, .{}>", k.join("."), r)),
            ShapeReference::CreateNestedOneInput(_, k) => f.write_str(&format!("CreateNestedOneInput<{}>", k.join("."))),
            ShapeReference::CreateNestedOneInputWithout(_, k, r) => f.write_str(&format!("CreateNestedOneInputWithout<{}, .{}>", k.join("."), r)),
            ShapeReference::CreateNestedManyInput(_, k) => f.write_str(&format!("CreateNestedManyInput<{}>", k.join("."))),
            ShapeReference::CreateNestedManyInputWithout(_, k, r) => f.write_str(&format!("CreateNestedManyInputWithout<{}, .{}>", k.join("."), r)),
            ShapeReference::UpdateInput(_, k) => f.write_str(&format!("UpdateInput<{}>", k.join("."))),
            ShapeReference::UpdateInputWithout(_, k, r) => f.write_str(&format!("UpdateInputWithout<{}, .{}>", k.join("."), r)),
            ShapeReference::UpdateNestedOneInput(_, k) => f.write_str(&format!("UpdateNestedOneInput<{}>", k.join("."))),
            ShapeReference::UpdateNestedOneInputWithout(_, k, r) => f.write_str(&format!("UpdateNestedOneInputWithout<{}, .{}>", k.join("."), r)),
            ShapeReference::UpdateNestedManyInput(_, k) => f.write_str(&format!("UpdateNestedManyInput<{}>", k.join("."))),
            ShapeReference::UpdateNestedManyInputWithout(_, k, r) => f.write_str(&format!("UpdateNestedManyInputWithout<{}, .{}>", k.join("."), r)),
            ShapeReference::ConnectOrCreateInput(_, k) => f.write_str(&format!("ConnectOrCreateInput<{}>", k.join("."))),
            ShapeReference::ConnectOrCreateInputWithout(_, k, r) => f.write_str(&format!("ConnectOrCreateInputWithout<{}, .{}>", k.join("."), r)),
            ShapeReference::UpdateWithWhereUniqueInput(_, k) => f.write_str(&format!("UpdateWithWhereUniqueInput<{}>", k.join("."))),
            ShapeReference::UpdateWithWhereUniqueInputWithout(_, k, r) => f.write_str(&format!("UpdateWithWhereUniqueInput<{}, .{}>", k.join("."), r)),
            ShapeReference::UpsertWithWhereUniqueInput(_, k) => f.write_str(&format!("UpsertWithWhereUniqueInput<{}>", k.join("."))),
            ShapeReference::UpsertWithWhereUniqueInputWithout(_, k, r) => f.write_str(&format!("UpsertWithWhereUniqueInput<{}, .{}>", k.join("."), r)),
            ShapeReference::UpdateManyWithWhereInput(_, k) => f.write_str(&format!("UpdateManyWithWhereInput<{}>", k.join("."))),
            ShapeReference::UpdateManyWithWhereInputWithout(_, k, r) => f.write_str(&format!("UpdateManyWithWhereInput<{}, .{}>", k.join("."), r)),
            ShapeReference::Select(_, k) => f.write_str(&format!("Select<{}>", k.join("."))),
            ShapeReference::Include(_, k) => f.write_str(&format!("Include<{}>", k.join("."))),
            ShapeReference::OrderByInput(_, k) => f.write_str(&format!("OrderByInput<{}>", k.join("."))),
        }
    }
}