use std::collections::BTreeMap;
use std::fmt::{Display, Formatter};
use educe::Educe;
use serde::Serialize;
use crate::r#type::keyword::Keyword;
use crate::r#type::reference::Reference;
use crate::r#type::Type;

#[derive(Debug, Clone, Eq, Serialize)]
#[derive(Educe)]
#[educe(Hash, PartialEq)]
pub enum SynthesizedShapeReference {
    BoolFilter,
    BoolNullableFilter,
    IntFilter,
    IntNullableFilter,
    Int64Filter,
    Int64NullableFilter,
    Float32Filter,
    Float32NullableFilter,
    FloatFilter,
    FloatNullableFilter,
    DecimalFilter,
    DecimalNullableFilter,
    DateFilter,
    DateNullableFilter,
    DateTimeFilter,
    DateTimeNullableFilter,
    ObjectIdFilter,
    ObjectIdNullableFilter,
    StringFilter,
    StringNullableFilter,
    EnumFilter(Box<Type>),
    EnumNullableFilter(Box<Type>),
    ArrayFilter(Box<Type>),
    ArrayNullableFilter(Box<Type>),
    BoolWithAggregatesFilter,
    BoolNullableWithAggregatesFilter,
    IntWithAggregatesFilter,
    IntNullableWithAggregatesFilter,
    Int64WithAggregatesFilter,
    Int64NullableWithAggregatesFilter,
    Float32WithAggregatesFilter,
    Float32NullableWithAggregatesFilter,
    FloatWithAggregatesFilter,
    FloatNullableWithAggregatesFilter,
    DecimalWithAggregatesFilter,
    DecimalNullableWithAggregatesFilter,
    DateWithAggregatesFilter,
    DateNullableWithAggregatesFilter,
    DateTimeWithAggregatesFilter,
    DateTimeNullableWithAggregatesFilter,
    ObjectIdWithAggregatesFilter,
    ObjectIdNullableWithAggregatesFilter,
    StringWithAggregatesFilter,
    StringNullableWithAggregatesFilter,
    EnumWithAggregatesFilter(Box<Type>),
    EnumNullableWithAggregatesFilter(Box<Type>),
    ArrayWithAggregatesFilter(Box<Type>),
    ArrayNullableWithAggregatesFilter(Box<Type>),
    IntAtomicUpdateOperationInput,
    Int64AtomicUpdateOperationInput,
    Float32AtomicUpdateOperationInput,
    FloatAtomicUpdateOperationInput,
    DecimalAtomicUpdateOperationInput,
    ArrayAtomicUpdateOperationInput(Box<Type>),
    Args(Reference),
    FindManyArgs(Reference),
    FindFirstArgs(Reference),
    FindUniqueArgs(Reference),
    CreateArgs(Reference),
    UpdateArgs(Reference),
    UpsertArgs(Reference),
    CopyArgs(Reference),
    DeleteArgs(Reference),
    CreateManyArgs(Reference),
    UpdateManyArgs(Reference),
    CopyManyArgs(Reference),
    DeleteManyArgs(Reference),
    CountArgs(Reference),
    AggregateArgs(Reference),
    GroupByArgs(Reference),
    RelationFilter(Reference),
    ListRelationFilter(Reference),
    WhereInput(Reference),
    WhereUniqueInput(Reference),
    ScalarFieldEnum(Reference),
    ScalarWhereWithAggregatesInput(Reference),
    CountAggregateInputType(Reference),
    SumAggregateInputType(Reference),
    AvgAggregateInputType(Reference),
    MaxAggregateInputType(Reference),
    MinAggregateInputType(Reference),
    CreateInput(Reference),
    CreateInputWithout(Reference, String),
    CreateNestedOneInput(Reference),
    CreateNestedOneInputWithout(Reference, String),
    CreateNestedManyInput(Reference),
    CreateNestedManyInputWithout(Reference, String),
    UpdateInput(Reference),
    UpdateInputWithout(Reference, String),
    UpdateNestedOneInput(Reference),
    UpdateNestedOneInputWithout(Reference, String),
    UpdateNestedManyInput(Reference),
    UpdateNestedManyInputWithout(Reference, String),
    ConnectOrCreateInput(Reference),
    ConnectOrCreateInputWithout(Reference, String),
    UpdateWithWhereUniqueInput(Reference),
    UpdateWithWhereUniqueInputWithout(Reference, String),
    UpsertWithWhereUniqueInput(Reference),
    UpsertWithWhereUniqueInputWithout(Reference, String),
    UpdateManyWithWhereInput(Reference),
    UpdateManyWithWhereInputWithout(Reference, String),
    Select(Reference),
    Include(Reference),
    OrderByInput(Reference),
    Result(Reference),
    CountAggregateResult(Reference),
    SumAggregateResult(Reference),
    AvgAggregateResult(Reference),
    MinAggregateResult(Reference),
    MaxAggregateResult(Reference),
    AggregateResult(Reference),
    GroupByResult(Reference),
}

impl SynthesizedShapeReference {

    pub fn contains_generics(&self) -> bool {
        match self {
            SynthesizedShapeReference::EnumFilter(t) => t.contains_generics(),
            SynthesizedShapeReference::EnumNullableFilter(t) => t.contains_generics(),
            SynthesizedShapeReference::ArrayFilter(t) => t.contains_generics(),
            SynthesizedShapeReference::ArrayNullableFilter(t) => t.contains_generics(),
            SynthesizedShapeReference::EnumWithAggregatesFilter(t) => t.contains_generics(),
            SynthesizedShapeReference::EnumNullableWithAggregatesFilter(t) => t.contains_generics(),
            SynthesizedShapeReference::ArrayWithAggregatesFilter(t) => t.contains_generics(),
            SynthesizedShapeReference::ArrayNullableWithAggregatesFilter(t) => t.contains_generics(),
            SynthesizedShapeReference::ArrayAtomicUpdateOperationInput(t) => t.contains_generics(),
            _ => false,
        }
    }

    pub fn contains_keywords(&self) -> bool {
        match self {
            SynthesizedShapeReference::EnumFilter(t) => t.contains_keywords(),
            SynthesizedShapeReference::EnumNullableFilter(t) => t.contains_keywords(),
            SynthesizedShapeReference::ArrayFilter(t) => t.contains_keywords(),
            SynthesizedShapeReference::ArrayNullableFilter(t) => t.contains_keywords(),
            SynthesizedShapeReference::EnumWithAggregatesFilter(t) => t.contains_keywords(),
            SynthesizedShapeReference::EnumNullableWithAggregatesFilter(t) => t.contains_keywords(),
            SynthesizedShapeReference::ArrayWithAggregatesFilter(t) => t.contains_keywords(),
            SynthesizedShapeReference::ArrayNullableWithAggregatesFilter(t) => t.contains_keywords(),
            SynthesizedShapeReference::ArrayAtomicUpdateOperationInput(t) => t.contains_keywords(),
            _ => false,
        }
    }

    pub fn replace_generics(&self, map: &BTreeMap<String, Type>) -> Self {
        match self {
            SynthesizedShapeReference::EnumFilter(t) => SynthesizedShapeReference::EnumFilter(Box::new(t.replace_generics(map))),
            SynthesizedShapeReference::EnumNullableFilter(t) => SynthesizedShapeReference::EnumNullableFilter(Box::new(t.replace_generics(map))),
            SynthesizedShapeReference::ArrayFilter(t) => SynthesizedShapeReference::ArrayFilter(Box::new(t.replace_generics(map))),
            SynthesizedShapeReference::ArrayNullableFilter(t) => SynthesizedShapeReference::ArrayNullableFilter(Box::new(t.replace_generics(map))),
            SynthesizedShapeReference::EnumWithAggregatesFilter(t) => SynthesizedShapeReference::EnumWithAggregatesFilter(Box::new(t.replace_generics(map))),
            SynthesizedShapeReference::EnumNullableWithAggregatesFilter(t) => SynthesizedShapeReference::EnumNullableWithAggregatesFilter(Box::new(t.replace_generics(map))),
            SynthesizedShapeReference::ArrayWithAggregatesFilter(t) => SynthesizedShapeReference::ArrayWithAggregatesFilter(Box::new(t.replace_generics(map))),
            SynthesizedShapeReference::ArrayNullableWithAggregatesFilter(t) => SynthesizedShapeReference::ArrayNullableWithAggregatesFilter(Box::new(t.replace_generics(map))),
            SynthesizedShapeReference::ArrayAtomicUpdateOperationInput(t) => SynthesizedShapeReference::ArrayAtomicUpdateOperationInput(Box::new(t.replace_generics(map))),
            _ => self.clone(),
        }
    }

    pub fn replace_keywords(&self, map: &BTreeMap<Keyword, Type>) -> Self {
        match self {
            SynthesizedShapeReference::EnumFilter(t) => SynthesizedShapeReference::EnumFilter(Box::new(t.replace_keywords(map))),
            SynthesizedShapeReference::EnumNullableFilter(t) => SynthesizedShapeReference::EnumNullableFilter(Box::new(t.replace_keywords(map))),
            SynthesizedShapeReference::ArrayFilter(t) => SynthesizedShapeReference::ArrayFilter(Box::new(t.replace_keywords(map))),
            SynthesizedShapeReference::ArrayNullableFilter(t) => SynthesizedShapeReference::ArrayNullableFilter(Box::new(t.replace_keywords(map))),
            SynthesizedShapeReference::EnumWithAggregatesFilter(t) => SynthesizedShapeReference::EnumWithAggregatesFilter(Box::new(t.replace_keywords(map))),
            SynthesizedShapeReference::EnumNullableWithAggregatesFilter(t) => SynthesizedShapeReference::EnumNullableWithAggregatesFilter(Box::new(t.replace_keywords(map))),
            SynthesizedShapeReference::ArrayWithAggregatesFilter(t) => SynthesizedShapeReference::ArrayWithAggregatesFilter(Box::new(t.replace_keywords(map))),
            SynthesizedShapeReference::ArrayNullableWithAggregatesFilter(t) => SynthesizedShapeReference::ArrayNullableWithAggregatesFilter(Box::new(t.replace_keywords(map))),
            SynthesizedShapeReference::ArrayAtomicUpdateOperationInput(t) => SynthesizedShapeReference::ArrayAtomicUpdateOperationInput(Box::new(t.replace_keywords(map))),
            _ => self.clone(),
        }
    }
}

impl Display for SynthesizedShapeReference {

    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            SynthesizedShapeReference::BoolFilter => f.write_str("BoolFilter"),
            SynthesizedShapeReference::BoolNullableFilter => f.write_str("BoolNullableFilter"),
            SynthesizedShapeReference::IntFilter => f.write_str("IntFilter"),
            SynthesizedShapeReference::IntNullableFilter => f.write_str("IntNullableFilter"),
            SynthesizedShapeReference::Int64Filter => f.write_str("Int64Filter"),
            SynthesizedShapeReference::Int64NullableFilter => f.write_str("Int64NullableFilter"),
            SynthesizedShapeReference::Float32Filter => f.write_str("Float32Filter"),
            SynthesizedShapeReference::Float32NullableFilter => f.write_str("Float32NullableFilter"),
            SynthesizedShapeReference::FloatFilter => f.write_str("FloatFilter"),
            SynthesizedShapeReference::FloatNullableFilter => f.write_str("FloatNullableFilter"),
            SynthesizedShapeReference::DecimalFilter => f.write_str("DecimalFilter"),
            SynthesizedShapeReference::DecimalNullableFilter => f.write_str("DecimalNullableFilter"),
            SynthesizedShapeReference::DateFilter => f.write_str("DateFilter"),
            SynthesizedShapeReference::DateNullableFilter => f.write_str("DateNullableFilter"),
            SynthesizedShapeReference::DateTimeFilter => f.write_str("DateTimeFilter"),
            SynthesizedShapeReference::DateTimeNullableFilter => f.write_str("DateTimeNullableFilter"),
            SynthesizedShapeReference::ObjectIdFilter => f.write_str("ObjectIdFilter"),
            SynthesizedShapeReference::ObjectIdNullableFilter => f.write_str("ObjectIdNullableFilter"),
            SynthesizedShapeReference::StringFilter => f.write_str("StringFilter"),
            SynthesizedShapeReference::StringNullableFilter => f.write_str("StringNullableFilter"),
            SynthesizedShapeReference::EnumFilter(t) => f.write_str(&format!("EnumFilter<{}>", t.as_ref())),
            SynthesizedShapeReference::EnumNullableFilter(t) => f.write_str(&format!("EnumNullableFilter<{}>", t.as_ref())),
            SynthesizedShapeReference::ArrayFilter(t) => f.write_str(&format!("ArrayFilter<{}>", t.as_ref())),
            SynthesizedShapeReference::ArrayNullableFilter(t) => f.write_str(&format!("ArrayNullableFilter<{}>", t.as_ref())),
            SynthesizedShapeReference::BoolWithAggregatesFilter => f.write_str("BoolWithAggregatesFilter"),
            SynthesizedShapeReference::BoolNullableWithAggregatesFilter => f.write_str("BoolNullableWithAggregatesFilter"),
            SynthesizedShapeReference::IntWithAggregatesFilter => f.write_str("IntWithAggregatesFilter"),
            SynthesizedShapeReference::IntNullableWithAggregatesFilter => f.write_str("IntNullableWithAggregatesFilter"),
            SynthesizedShapeReference::Int64WithAggregatesFilter => f.write_str("Int64WithAggregatesFilter"),
            SynthesizedShapeReference::Int64NullableWithAggregatesFilter => f.write_str("Int64NullableWithAggregatesFilter"),
            SynthesizedShapeReference::Float32WithAggregatesFilter => f.write_str("Float32WithAggregatesFilter"),
            SynthesizedShapeReference::Float32NullableWithAggregatesFilter => f.write_str("Float32NullableWithAggregatesFilter"),
            SynthesizedShapeReference::FloatWithAggregatesFilter => f.write_str("FloatWithAggregatesFilter"),
            SynthesizedShapeReference::FloatNullableWithAggregatesFilter => f.write_str("FloatNullableWithAggregatesFilter"),
            SynthesizedShapeReference::DecimalWithAggregatesFilter => f.write_str("DecimalWithAggregatesFilter"),
            SynthesizedShapeReference::DecimalNullableWithAggregatesFilter => f.write_str("DecimalNullableWithAggregatesFilter"),
            SynthesizedShapeReference::DateWithAggregatesFilter => f.write_str("DateWithAggregatesFilter"),
            SynthesizedShapeReference::DateNullableWithAggregatesFilter => f.write_str("DateNullableWithAggregatesFilter"),
            SynthesizedShapeReference::DateTimeWithAggregatesFilter => f.write_str("DateTimeWithAggregatesFilter"),
            SynthesizedShapeReference::DateTimeNullableWithAggregatesFilter => f.write_str("DateTimeNullableWithAggregatesFilter"),
            SynthesizedShapeReference::ObjectIdWithAggregatesFilter => f.write_str("ObjectIdWithAggregatesFilter"),
            SynthesizedShapeReference::ObjectIdNullableWithAggregatesFilter => f.write_str("ObjectIdNullableWithAggregatesFilter"),
            SynthesizedShapeReference::StringWithAggregatesFilter => f.write_str("StringWithAggregatesFilter"),
            SynthesizedShapeReference::StringNullableWithAggregatesFilter => f.write_str("StringNullableWithAggregatesFilter"),
            SynthesizedShapeReference::EnumWithAggregatesFilter(t) => f.write_str(&format!("EnumWithAggregatesFilter<{}>", t.as_ref())),
            SynthesizedShapeReference::EnumNullableWithAggregatesFilter(t) => f.write_str(&format!("EnumNullableWithAggregatesFilter<{}>", t.as_ref())),
            SynthesizedShapeReference::ArrayWithAggregatesFilter(t) => f.write_str(&format!("ArrayWithAggregatesFilter<{}>", t.as_ref())),
            SynthesizedShapeReference::ArrayNullableWithAggregatesFilter(t) => f.write_str(&format!("ArrayNullableWithAggregatesFilter<{}>", t.as_ref())),
            SynthesizedShapeReference::IntAtomicUpdateOperationInput => f.write_str("IntAtomicUpdateOperationInput"),
            SynthesizedShapeReference::Int64AtomicUpdateOperationInput => f.write_str("Int64AtomicUpdateOperationInput"),
            SynthesizedShapeReference::Float32AtomicUpdateOperationInput => f.write_str("Float32AtomicUpdateOperationInput"),
            SynthesizedShapeReference::FloatAtomicUpdateOperationInput => f.write_str("FloatAtomicUpdateOperationInput"),
            SynthesizedShapeReference::DecimalAtomicUpdateOperationInput => f.write_str("DecimalAtomicUpdateOperationInput"),
            SynthesizedShapeReference::ArrayAtomicUpdateOperationInput(t) => f.write_str(&format!("ArrayAtomicUpdateOperationInput{}", t.as_ref())),
            SynthesizedShapeReference::Args(re) => f.write_str(&format!("Args<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::FindManyArgs(re) => f.write_str(&format!("FindManyArgs<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::FindFirstArgs(re) => f.write_str(&format!("FindFirstArgs<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::FindUniqueArgs(re) => f.write_str(&format!("FindUniqueArgs<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::CreateArgs(re) => f.write_str(&format!("CreateArgs<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::UpdateArgs(re) => f.write_str(&format!("UpdateArgs<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::UpsertArgs(re) => f.write_str(&format!("UpsertArgs<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::CopyArgs(re) => f.write_str(&format!("CopyArgs<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::DeleteArgs(re) => f.write_str(&format!("DeleteArgs<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::CreateManyArgs(re) => f.write_str(&format!("CreateManyArgs<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::UpdateManyArgs(re) => f.write_str(&format!("UpdateManyArgs<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::CopyManyArgs(re) => f.write_str(&format!("CopyManyArgs<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::DeleteManyArgs(re) => f.write_str(&format!("DeleteManyArgs<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::CountArgs(re) => f.write_str(&format!("CountArgs<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::AggregateArgs(re) => f.write_str(&format!("AggregateArgs<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::GroupByArgs(re) => f.write_str(&format!("GroupByArgs<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::RelationFilter(re) => f.write_str(&format!("RelationFilter<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::ListRelationFilter(re) => f.write_str(&format!("ListRelationFilter<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::WhereInput(re) => f.write_str(&format!("WhereInput<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::WhereUniqueInput(re) => f.write_str(&format!("WhereUniqueInput<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::ScalarFieldEnum(re) => f.write_str(&format!("ScalarFieldEnum<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::ScalarWhereWithAggregatesInput(re) => f.write_str(&format!("ScalarWhereWithAggregatesInput<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::CountAggregateInputType(re) => f.write_str(&format!("CountAggregateInputType<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::SumAggregateInputType(re) => f.write_str(&format!("SumAggregateInputType<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::AvgAggregateInputType(re) => f.write_str(&format!("AvgAggregateInputType<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::MaxAggregateInputType(re) => f.write_str(&format!("MaxAggregateInputType<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::MinAggregateInputType(re) => f.write_str(&format!("MinAggregateInputType<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::CreateInput(re) => f.write_str(&format!("CreateInput<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::CreateInputWithout(re, r) => f.write_str(&format!("CreateInputWithout<{}, .{}>", re.string_path().join("."), r)),
            SynthesizedShapeReference::CreateNestedOneInput(re) => f.write_str(&format!("CreateNestedOneInput<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::CreateNestedOneInputWithout(re, r) => f.write_str(&format!("CreateNestedOneInputWithout<{}, .{}>", re.string_path().join("."), r)),
            SynthesizedShapeReference::CreateNestedManyInput(re) => f.write_str(&format!("CreateNestedManyInput<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::CreateNestedManyInputWithout(re, r) => f.write_str(&format!("CreateNestedManyInputWithout<{}, .{}>", re.string_path().join("."), r)),
            SynthesizedShapeReference::UpdateInput(re) => f.write_str(&format!("UpdateInput<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::UpdateInputWithout(re, r) => f.write_str(&format!("UpdateInputWithout<{}, .{}>", re.string_path().join("."), r)),
            SynthesizedShapeReference::UpdateNestedOneInput(re) => f.write_str(&format!("UpdateNestedOneInput<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::UpdateNestedOneInputWithout(re, r) => f.write_str(&format!("UpdateNestedOneInputWithout<{}, .{}>", re.string_path().join("."), r)),
            SynthesizedShapeReference::UpdateNestedManyInput(re) => f.write_str(&format!("UpdateNestedManyInput<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::UpdateNestedManyInputWithout(re, r) => f.write_str(&format!("UpdateNestedManyInputWithout<{}, .{}>", re.string_path().join("."), r)),
            SynthesizedShapeReference::ConnectOrCreateInput(re) => f.write_str(&format!("ConnectOrCreateInput<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::ConnectOrCreateInputWithout(re, r) => f.write_str(&format!("ConnectOrCreateInputWithout<{}, .{}>", re.string_path().join("."), r)),
            SynthesizedShapeReference::UpdateWithWhereUniqueInput(re) => f.write_str(&format!("UpdateWithWhereUniqueInput<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::UpdateWithWhereUniqueInputWithout(re, r) => f.write_str(&format!("UpdateWithWhereUniqueInput<{}, .{}>", re.string_path().join("."), r)),
            SynthesizedShapeReference::UpsertWithWhereUniqueInput(re) => f.write_str(&format!("UpsertWithWhereUniqueInput<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::UpsertWithWhereUniqueInputWithout(re, r) => f.write_str(&format!("UpsertWithWhereUniqueInput<{}, .{}>", re.string_path().join("."), r)),
            SynthesizedShapeReference::UpdateManyWithWhereInput(re) => f.write_str(&format!("UpdateManyWithWhereInput<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::UpdateManyWithWhereInputWithout(re, r) => f.write_str(&format!("UpdateManyWithWhereInput<{}, .{}>", re.string_path().join("."), r)),
            SynthesizedShapeReference::Select(re) => f.write_str(&format!("Select<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::Include(re) => f.write_str(&format!("Include<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::OrderByInput(re) => f.write_str(&format!("OrderByInput<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::Result(re) => f.write_str(&format!("Result<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::CountAggregateResult(re) => f.write_str(&format!("CountAggregateResult<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::SumAggregateResult(re) => f.write_str(&format!("SumAggregateResult<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::AvgAggregateResult(re) => f.write_str(&format!("AvgAggregateResult<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::MinAggregateResult(re) => f.write_str(&format!("MinAggregateResult<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::MaxAggregateResult(re) => f.write_str(&format!("MaxAggregateResult<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::AggregateResult(re) => f.write_str(&format!("AggregateResult<{}>", re.string_path().join("."))),
            SynthesizedShapeReference::GroupByResult(re) => f.write_str(&format!("GroupByResult<{}>", re.string_path().join("."))),
        }
    }
}